
import "./globals.css";



export const metadata = {
  title: "Ciudad Salud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" cz-shortcut-listen>
      <body>{children}</body>
    </html>
  );
}
