
import "./globals.css";
import Admin from "@/context/Admin";


export const metadata = {
  title: "Ciudad Salud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen w-screen">
        <Admin>{children}</Admin>
        </body>
    </html>
  );
}
